#ifndef VOLE_MACHINE_SIMULATOR_SRC_BACK_END_VOLE_MACHINE_H
#define VOLE_MACHINE_SIMULATOR_SRC_BACK_END_VOLE_MACHINE_H

#include <bits/stdc++.h>

using namespace std;



#endif  // VOLE_MACHINE_SIMULATOR_SRC_BACK_END_VOLE_MACHINE_H